[package]
name = "lingua-rs"
version = "0.1.0"
authors = ["Adam Brady <adam@boxxen.org>"]
edition = "2018"

[dependencies]
regex = "1.3.9"
lazy_static = "1.4.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
